Repository anuragverma108/WildGuard, pull requests merged in 2024-10, with the labels that each got.

#19 added scroll to top but with a leaf
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted, hactoberfest

#60 Adding the Separate Contact-Us Page
  Contact-Us/index.html
  Contact-Us/script.js
  Contact-Us/style.css
  index.html
Labels: hacktoberfest-accepted, hactoberfest

#69 Added Search Functionality in Homepage
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted, hactoberfest

#70 Feature/add terms of use page
  index.html
  terms-of-use.html
Labels: hacktoberfest-accepted, hactoberfest

#105 fixing issue #43
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hactoberfest

#172 Project Documentation Improved : Detailed README added
  README.md
Labels: hacktoberfest-accepted, hactoberfest

#170 Add Events Data and Render it Dyanically on it unified UI
  Become-a-Partner/index.html
  Become-a-Partner/script.js
  Become-a-Partner/style.css
  Events-Data/modal-scripts.js
  Events-Data/modal.css
  index.html
Labels: hacktoberfest-accepted, hactoberfest

#175 Uploding my PR for review and made sure there are no conflicting files #88
  assets/css/saveNature.css
  assets/images/awareness-icon.png
  assets/images/carbon-icon.png
  assets/images/community-icon.png
  assets/images/energy-icon.png
  assets/images/ocean-icon.png
  assets/images/plastic-icon.png
  assets/images/recycle-icon.png
  assets/images/species-icon.png
  assets/images/tree-icon.png.png
  assets/images/water-icon.png
  index.html
  saveNature.html
Labels: hacktoberfest-accepted, hactoberfest

#154 🔗 Improve Navigation: Back Button Added to Policy, Terms, and Contact Us!
  Contact-Us/index.html
  Contact-Us/style.css
  privacy-policy.html
  terms-of-use.html
Labels: hacktoberfest-accepted, hactoberfest

#123 Updated the button
  assets/css/style.css
Labels: hacktoberfest-accepted, hactoberfest

#126 Added text for about with 3 buttons
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#128 added community page and linked contact page also
  Community/index.html
  Community/script.js
  Community/style.css
  assets/images/community-hero-bg.jpeg
  assets/images/community-hero-bg.png
  index.html
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#150 Added donation.html page
  Donation.html
  assets/images/animals.jpg
Labels: hacktoberfest-accepted, hactoberfest

#142 issue #141 fixed English and Read More button
  Contact-Us/style.css
  assets/css/style.css
  index.html
  partner/partner.css
  partner/partner.html
  partner/script.js
Labels: hacktoberfest-accepted, hactoberfest

#243 Added language Translation Feature
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#242 Fix vision and next plan button click issue ##16
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#248 🛠️ Re-add Terms of Use Page and Resolve Conflicts (as suggested by maintainer @anuragverma108)
  index.html
  terms-of-use.html
Labels: hacktoberfest-accepted, hacktoberfest

#249 Added Buttons hover effect
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#332 Modified leaf icon
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#260 Added Login Functionality
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#259 Added image carousel on banner-row for smaller screen width devices ISSUE #42
  assets/css/style.css
  assets/js/carousel.js
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#272 Spelling mistake corrected and Added hover effects on few buttons #252
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#275 ✨ Re-add Contact Form with Enhanced UI and Green Pistachio Theme 🍃
  Contact.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#448 #373 Donation and NGO page for this Wildlife website
  Donation.html
  index.html
  terms-of-use.html
Labels: hacktoberfest-accepted, hacktoberfest

#340 Fixed the footer aligment and margin
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#348 Add hover effect on `Become a partner` Button
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#349 Changed email input field text color to white #347
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#352 Contact Link is working perfectly now
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#366 Interactive Donation Form Added
  assets/images/bg form.jpg
  donate.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#368 Fixed nav bar, nav links highlighting, about section text-alignment
  assets/css/style.css
  contributing.md
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#371 Adding progress bar on the top of the page. #125
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#376 Resolved merge conflicts and added missing alt tag #95
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#686 Issue #1 Added text to cards in place of irrelevant messages
  index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#665 Resolved the conflicts for become partner page
  Become-a-Partner/index.html
  Become-a-Partner/script.js
  Become-a-Partner/style.css
  Donation.html
  assets/css/login.css
  assets/css/style.css
  assets/images/facebook.png
  assets/images/google.png
  assets/images/instagram.png
  assets/images/social.png
  assets/js/carousel.js
  assets/js/script.js
  index.html
  login.html
  register.html
Labels: hacktoberfest-accepted, hacktoberfest

#666 ISSUE #198: Removed Terms of use and Privacy & Policy in footer and added WildGuard Logo in the footer
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#668 Sakshi view event feature
  Events-Data/modal-scripts.js
  Events-Data/modal.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#677 fixed menu bg on small screen
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#681 default_content_of_about
  .vscode/settings.json
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#685 added pop up
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#690 📬 Add Contact Us Page to WildGuard Website In Footer Section🌐
  Contact.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#693 feat: added pr and issue template
  .github/templates/pull_request_template.md
  index.html
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#697 changed the height of the navbar and improvised underlines on navbar …
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#710 Added saveNature.html and css and remove the nav bar conflict
  SaveNature.html
  assets/css/SaveNature.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#712 Enhanced the README File for better clarity
  README.md
  about.png
  donate.png
  donation.png
  home.png
  service.png
Labels: hacktoberfest-accepted, hacktoberfest

#716 FAQ page added
  faq.html
Labels: hacktoberfest-accepted, hacktoberfest

#727 about issue and about page added #724
  about.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#729 social media links added #725
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#742 Added new moreevents page and fixed more event button in index file
  index.html
  moreevents.html
Labels: hacktoberfest-accepted, hacktoberfest

#745 Fixed working of navbar. Issue #744
  assets/js/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#746 ADD RATING/REVIEW PAGE IN FOOTER SECTION BUTTON #732
  image.avif
  index.html
  login.html
  review.html
Labels: hacktoberfest-accepted, hacktoberfest

#747 Bottom Footer and Redundant Links
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#749 Redesigned more events
  moreevents.html
Labels: hacktoberfest-accepted, hacktoberfest

#750 Fixed login/register & conflict issues #719
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#756 changed alignment
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#798 Add accordion section in index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#998 Changing ui of Contact Us page and its working. #751
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1015 Revert "Changing ui of Contact Us page and its working. #751"
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#996 Improve form validation error message design fix #978
  donate.html
  package-lock.json
Labels: hacktoberfest-accepted, hacktoberfest

#999 #997 clicking on donate now under the 'support us with your donations' section redirects to donation website
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1003 [Enhancement] Enhanced about page
  about.html
  assets/css/about.css
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#1004 Resolved merge conflicts #936
  SaveOcean.html
  assets/images/awareness.svg
  assets/images/clean-energy.svg
  assets/images/cut-plastic.svg
  assets/images/fish.svg
  assets/images/involved.svg
  assets/images/laws.svg
  assets/images/marine.svg
  assets/images/plant-trees.svg
  assets/images/reduce-plastic.svg
  assets/images/research.svg
  assets/images/water.svg
Labels: hacktoberfest-accepted

#1011 fixes- #1007 Cross not working in view event tile
  index.html
Labels: hacktoberfest-accepted

#1014 Enhance Register Page UI
  assets/css/register.css
  register.html
Labels: hacktoberfest-accepted

#1018 Fixes- #1016 User alerted with Thank you for ur feedback only when input field not empty
  assets/css/style.css
  assets/js/carousel.js
  index.html
Labels: hacktoberfest-accepted

#1020 Fixes- #1019 Improved the Impact of UR donation UI
  style.css
Labels: hacktoberfest-accepted

#1021 Responsive Footer
  assets/css/style.css
Labels: hacktoberfest-accepted

#1055 FAQ's modification looks better after this for User experience
  faq.css
  faq.html
Labels: hacktoberfest-accepted, hacktoberfest

#1057 Revert "FAQ's modification looks better after this for User experience"
  faq.css
  faq.html
Labels: hacktoberfest-accepted, hacktoberfest

#1056 "Our Testimonials" Text Not Visible Due to Color Contrast - Issue #1054 Resolved
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1068 Fixed Donate Section
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1069 #1063 fixed Support us cards
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1075 Linked User Icon to New User Page
  index.html
  user.html
Labels: hacktoberfest-accepted, hacktoberfest

#1076 Please check, I have resolved the Conflicts raised in the Navbar.
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1109 Rectified UI of Save Ecology
  SaveEcology.html
  assets/images/air-icon.png
  assets/images/climate-icon.png
  assets/images/forest-icon.png
  assets/images/plant-icon.png
Labels: hacktoberfest-accepted, hacktoberfest

#1106 login and signup ui improved
  assets/css/style.css
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1104 Cursor Pointer Not Displayed on Hover for Tree Plantation Card
  assets/css/style.css
Labels: hacktoberfest-accepted

#1085 Fixed the alignment of search button
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1086 Added CODE_OF_CONDUCT.md file to the repository
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted, hacktoberfest

#1090 [Enhancement] Redesgined contact page
  Contact.html
  assets/css/contact.css
Labels: hacktoberfest-accepted, hacktoberfest

#1093 changed readme
  README.md
  donate.html
Labels: hacktoberfest-accepted, hacktoberfest

#1095 Redirects to home page when logo is clicked
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1100 Add contact us/#4 updated
  about.html
  assets/css/about.css
Labels: hacktoberfest-accepted, hacktoberfest

#1117 Fix: Search Bar Layout and Input Sizing.
  assets/css/style.css
  donate.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1139 fixed the image size in donate section and corrected some CSS #1111 #1141
  assets/css/style.css
  index.html
  style_changed.css
Labels: hacktoberfest-accepted, hacktoberfest

#1183 Enhancement of contact us page
  Contact.html
Labels: hacktoberfest-accepted, hacktoberfest

#1190 Enhanced UI FOR Save.html file issue no #1189
  SaveNature.html
  assets/css/SaveNature.css
  event1.html
  event2.html
  event3.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1203 Added a Scroll Down Progress Bar Matched to the Website Design Theme
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1186 added some styling on Navbar section #1185
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1255 Improved button UI for 'Learn More,' 'Donate Now,' and 'See Event' #1250
  index.html
  style.css
  styles.css
  stylesss.css
Labels: hacktoberfest-accepted, hacktoberfest

#1214 Hover Effect Added !
  WildGuard-main/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1221 [Enhancement] Redesign Donation form and Greatly Improve the Downloadable Receipt
  assets/css/donate-form.css
  assets/js/donate-form.js
  donate.html
Labels: hacktoberfest-accepted, hacktoberfest

#1226 Responsiveness of the page added
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1234 Improved the alignment of donation cards #1232
  assets/css/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#1235 Fixed donation card button alignment
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1237 Improved the structure of service cards #1230
  assets/css/style.css
  index.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#1238 Enhanced UI issue No #1236
  Events-Data/modal.css
  SaveEcology.html
  SaveOcean.html
  TreePlantation.html
  about.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1240 Added the few questions in FAQ section #1237
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1246 user profile updated (issue-#1245)
  user.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#1247 updation and content alignment in donation plane cards
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1249 Mobile and Tablet View: Contact Us Page Now Fully Responsive#1222
  Contact.html
Labels: hacktoberfest-accepted, hacktoberfest

#1254 Create SECURITY.md
  SECURITY.md
Labels: hacktoberfest-accepted, hacktoberfest

#1262 Hover effect successfully added to Login & Register Buttons
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1268 Fix: Issue #1141 fixed the form and its appearance
  assets/css/style.css
  review.html
Labels: hacktoberfest-accepted, hacktoberfest

#1272 Solved Linked about.html to about.css and added image #1271
  about.html
  assets/css/about.css
Labels: hacktoberfest-accepted, hacktoberfest

#1274 [fix] Navbar User Icon Rounded and Resized (#1273)
  assets/css/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1289 #1288 added the donation website on clicking donate now in the learn more website
  learnmore.html
Labels: hacktoberfest-accepted, hacktoberfest

#1312 alignment
  styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#1320 Updated the Donation link
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1322 [UI]Partner Section UI Enhancement
  assets/css/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1326 fixed the toggle button bug
  index.html
  login.html
Labels: hacktoberfest-accepted, hacktoberfest

#1330 Updated Branch With Current Branch
  .github/templates/pull_request_template.md
  index.html
  register.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1333 Create service.html
  service.html
Labels: hacktoberfest-accepted, hacktoberfest

#1334 Center the Submit Button to Improve UI Interactivity #1276
  index.html
  stylesss.css
Labels: hacktoberfest-accepted, hacktoberfest

#1339 Transition effect for 'Our Core Values' in About Us(about.html)
  about.html
Labels: hacktoberfest-accepted, hacktoberfest

#1389 Styles: add padding around feature list | add margin in donation button
  assets/css/style.css
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1397 Revert "Styles: add padding around feature list | add margin in donation button"
  assets/css/style.css
  index.html
  style.css
Labels: hacktoberfest-accepted

#1395 Fix: Correct capitalization of "Y" in New York and adjust grammar in description
  index.html
Labels: hacktoberfest-accepted

#1388 Added UI in cleanocean.html page
  assets/images/cleanOcean.jpg
  cleanocean.html
Labels: hacktoberfest-accepted

#1387 Enhanced the ui in in SaveNature.html,SaveEcology.html and SaveOcean.…
  SaveNature.html
  assets/css/SaveNature.css
Labels: hacktoberfest-accepted, hacktoberfest

#1350 Fix validation of input fields in sign up form
  assets/css/register.css
  register.html
Labels: hacktoberfest-accepted

#1354 Updated the Rate Us Page #1328
  review.html
Labels: hacktoberfest-accepted, hacktoberfest

#1360 Changed Styling of the login page
  login.html
Labels: hacktoberfest-accepted

#1361 Redesign rateus page #1265
  assets/css/review.css
  index.html
  review.html
Labels: hacktoberfest-accepted, hacktoberfest

#1367 Added footer, added navbar and updated the css
  about.html
  assets/images/community.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#1370 Nav menus animation smoothness improved and button spacing fix #1365
  assets/css/style.css
  style.css
Labels: hacktoberfest-accepted

#1372 Added Go To Bottom Button
  index.html
  style.css
Labels: hacktoberfest-accepted

#1377 Created the DMCA and Disclaimer Pages
  Contact.html
  disclaimer.html
  dmca.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#1399 Revert "Created the DMCA and Disclaimer Pages "
  Contact.html
  disclaimer.html
  dmca.html
  index.html
Labels: hacktoberfest-accepted

#1405 implemented the search functionality
  assets/css/searchbar.css
  assets/js/search-index.js
  assets/js/search.js
  index.html
Labels: hacktoberfest-accepted

#1374 #1373 Solved - Updated CSS for login page with enhanced styles and interactivity
  login.html
Labels: hacktoberfest-accepted, hacktoberfest

#1383 Fixed UI of values cards and team cards
  about.html
Labels: hacktoberfest-accepted, hacktoberfest

#1406 UI Improvement Suggestions for Donation Page #1401
  Donation.html
Labels: hacktoberfest-accepted, hacktoberfest

#1409 Social Login options added #1391
  Loginpage.html
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#1424 Changed "Safe water" to "Save water" in the Home Section
  index.html
Labels: hacktoberfest-accepted

#1455 Improved Hover effect of become a partner button.
  assets/css/style.css
Labels: hacktoberfest-accepted

#1480 Added Calendar button in more events which popups the calendar that highlights the upcoming events of wildlife website .
  moreevents.html
Labels: hacktoberfest-accepted, hacktoberfest

#1489 Added a new feature -- " Eco-Friendly Shop" Issue No.---#1488
  EcoFriendlyShop.html
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1431 [Fixed]scroll-to-bottom arrow alignment (#1430)
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1485 added google login functionality to login page add api key
  login.html
  login.js
Labels: hacktoberfest-accepted

#1428 Added spacing between textarea in conservation forum #1426
  assets/css/style.css
Labels: hacktoberfest-accepted

#1514 Fixed the button ("Shop Now" Button Becomes Unclickable on Rotating Card Component)
  index.html
Labels: hacktoberfest-accepted

#1419 [Enhancement]registration page- password match validation, extra login options, UI fixes
  .DS_Store
  .gitignore
  assets/css/register.css
  register.html
Labels: hacktoberfest-accepted, hacktoberfest

#1442 CSS of the navbar and the cards is increased
  assets/css/style.css
  style.css
  style_changed.css
Labels: hacktoberfest-accepted, hacktoberfest

#1443 Fixes #1441 : Made Learn More page responsive
  styles.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#1447 fix: align hero subtitle, adjust gallery position, and improve donation button spacing
  assets/css/style.css
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#1462 Add margin between the Donation button and the line above (#1461)
  assets/css/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#1468 fix : added css to service page
  service.html
Labels: hacktoberfest-accepted, hacktoberfest

#1476 Issue:#1474 solved "Enhanced the UI of donation form appearance with updated styles and layout"
  Donation.html
Labels: hacktoberfest-accepted, hacktoberfest

#1496 Implement Enhanced Copyright Policy Page Design #1495
  copyright.html
Labels: hacktoberfest-accepted, hacktoberfest

#1497 Enhanced Ui for login.html
  login.html
Labels: hacktoberfest-accepted, hacktoberfest
